logFilters:
  - level: discard
    pattern: '*@npm:* The darwin-* architecture'

nodeLinker: node-modules

packageExtensions:
  '@chakra-ui/cli@*':
    peerDependencies:
      '@types/node': '*'
      typescript: '*'
  '@chakra-ui/props-docs@*':
    peerDependencies:
      '@emotion/react': '*'
      '@emotion/styled': '*'
      framer-motion: '*'
      react: '*'
      react-dom: '*'
      typescript: '*'
  '@chakra-ui/toast@*':
    peerDependencies:
      '@emotion/react': '*'
      '@emotion/styled': '*'

plugins:


